#pragma checksum "PageFiles\Utility\Messaging\pgRespondToMessage.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "039D1C46FBB6BE519D6F2ED679327F8EE16F15A87235E87F14329CBDB03B65D8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer {
    
    
    /// <summary>
    /// pgRespondToMessage
    /// </summary>
    public partial class pgRespondToMessage : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSend;
        
        #line default
        #line hidden
        
        
        #line 11 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtMessage;
        
        #line default
        #line hidden
        
        
        #line 12 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lbMessage;
        
        #line default
        #line hidden
        
        
        #line 13 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lbMember;
        
        #line default
        #line hidden
        
        
        #line 15 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblRemaining;
        
        #line default
        #line hidden
        
        
        #line 17 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblChat;
        
        #line default
        #line hidden
        
        
        #line 19 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image imgMember;
        
        #line default
        #line hidden
        
        
        #line 21 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblMemberName;
        
        #line default
        #line hidden
        
        
        #line 22 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSend1_Copy;
        
        #line default
        #line hidden
        
        
        #line 23 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtMemberId;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/utility/messaging/pgrespondt" +
                    "omessage.xaml", System.UriKind.Relative);
            
            #line 1 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 8 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            ((Extremely_Casual_Game_Organizer.pgRespondToMessage)(target)).Loaded += new System.Windows.RoutedEventHandler(this.chatWith);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSend = ((System.Windows.Controls.Button)(target));
            
            #line 10 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            this.btnSend.Click += new System.Windows.RoutedEventHandler(this.btnSend_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.txtMessage = ((System.Windows.Controls.TextBox)(target));
            
            #line 11 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            this.txtMessage.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.txtMessage_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.lbMessage = ((System.Windows.Controls.ListBox)(target));
            return;
            case 5:
            this.lbMember = ((System.Windows.Controls.ListBox)(target));
            
            #line 13 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            this.lbMember.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.lbMember_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.lblRemaining = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.lblChat = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.imgMember = ((System.Windows.Controls.Image)(target));
            return;
            case 9:
            this.lblMemberName = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.btnSend1_Copy = ((System.Windows.Controls.Button)(target));
            
            #line 22 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            this.btnSend1_Copy.Click += new System.Windows.RoutedEventHandler(this.btnSend1_Copy_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.txtMemberId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            
            #line 24 "PageFiles\Utility\Messaging\pgRespondToMessage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

