#pragma checksum "PageFiles\Leagues\pgAddEditLeague.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "89E36B0F1549A692D504C11C358DC18766048188DD8FF21C4E5B3DC27F069F01"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer {
    
    
    /// <summary>
    /// pgAddEditLeague
    /// </summary>
    public partial class pgAddEditLeague : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblName;
        
        #line default
        #line hidden
        
        
        #line 33 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtLeagueID;
        
        #line default
        #line hidden
        
        
        #line 40 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtName;
        
        #line default
        #line hidden
        
        
        #line 47 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cboSport;
        
        #line default
        #line hidden
        
        
        #line 54 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider sldDues;
        
        #line default
        #line hidden
        
        
        #line 57 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDues;
        
        #line default
        #line hidden
        
        
        #line 64 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chkStatus;
        
        #line default
        #line hidden
        
        
        #line 69 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cboGender;
        
        #line default
        #line hidden
        
        
        #line 73 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBoxItem selectionMale;
        
        #line default
        #line hidden
        
        
        #line 74 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBoxItem selectionFemale;
        
        #line default
        #line hidden
        
        
        #line 75 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBoxItem selectionEitherGender;
        
        #line default
        #line hidden
        
        
        #line 81 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtMaxTeams;
        
        #line default
        #line hidden
        
        
        #line 88 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDetails;
        
        #line default
        #line hidden
        
        
        #line 91 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnEditSave;
        
        #line default
        #line hidden
        
        
        #line 100 "PageFiles\Leagues\pgAddEditLeague.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/leagues/pgaddeditleague.xaml" +
                    "", System.UriKind.Relative);
            
            #line 1 "PageFiles\Leagues\pgAddEditLeague.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "PageFiles\Leagues\pgAddEditLeague.xaml"
            ((Extremely_Casual_Game_Organizer.pgAddEditLeague)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblName = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.txtLeagueID = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.txtName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.cboSport = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.sldDues = ((System.Windows.Controls.Slider)(target));
            return;
            case 7:
            this.txtDues = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.chkStatus = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 9:
            this.cboGender = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.selectionMale = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 11:
            this.selectionFemale = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 12:
            this.selectionEitherGender = ((System.Windows.Controls.ComboBoxItem)(target));
            return;
            case 13:
            this.txtMaxTeams = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.txtDetails = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.btnEditSave = ((System.Windows.Controls.Button)(target));
            
            #line 91 "PageFiles\Leagues\pgAddEditLeague.xaml"
            this.btnEditSave.Click += new System.Windows.RoutedEventHandler(this.btnEditSave_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 100 "PageFiles\Leagues\pgAddEditLeague.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

