#pragma checksum "PageFiles\MemberPages\pgMemberProfile.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A2008755F4FD377E2967477B60122BDE95114CAD04FC81F239FA5B4B371B6E3B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer {
    
    
    /// <summary>
    /// pgMemberProfile
    /// </summary>
    public partial class pgMemberProfile : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image img;
        
        #line default
        #line hidden
        
        
        #line 11 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnEditProfile;
        
        #line default
        #line hidden
        
        
        #line 14 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblName;
        
        #line default
        #line hidden
        
        
        #line 15 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmail;
        
        #line default
        #line hidden
        
        
        #line 16 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPhone;
        
        #line default
        #line hidden
        
        
        #line 17 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGender;
        
        #line default
        #line hidden
        
        
        #line 20 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeamTitle;
        
        #line default
        #line hidden
        
        
        #line 22 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lbTeam;
        
        #line default
        #line hidden
        
        
        #line 26 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDeleteTeam;
        
        #line default
        #line hidden
        
        
        #line 27 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreateTeam;
        
        #line default
        #line hidden
        
        
        #line 31 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtBio;
        
        #line default
        #line hidden
        
        
        #line 32 "PageFiles\MemberPages\pgMemberProfile.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button brnEditBio;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/memberpages/pgmemberprofile." +
                    "xaml", System.UriKind.Relative);
            
            #line 1 "PageFiles\MemberPages\pgMemberProfile.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.img = ((System.Windows.Controls.Image)(target));
            return;
            case 2:
            this.btnEditProfile = ((System.Windows.Controls.Button)(target));
            
            #line 11 "PageFiles\MemberPages\pgMemberProfile.xaml"
            this.btnEditProfile.Click += new System.Windows.RoutedEventHandler(this.btnEditProfile_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.lblName = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblPhone = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblGender = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.lblTeamTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.lbTeam = ((System.Windows.Controls.ListBox)(target));
            return;
            case 9:
            this.btnDeleteTeam = ((System.Windows.Controls.Button)(target));
            
            #line 26 "PageFiles\MemberPages\pgMemberProfile.xaml"
            this.btnDeleteTeam.Click += new System.Windows.RoutedEventHandler(this.btnDeleteTeam_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnCreateTeam = ((System.Windows.Controls.Button)(target));
            
            #line 27 "PageFiles\MemberPages\pgMemberProfile.xaml"
            this.btnCreateTeam.Click += new System.Windows.RoutedEventHandler(this.btnCreateTeam_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.txtBio = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.brnEditBio = ((System.Windows.Controls.Button)(target));
            
            #line 32 "PageFiles\MemberPages\pgMemberProfile.xaml"
            this.brnEditBio.Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

