#pragma checksum "PageFiles\Teams\pgViewTeamDetails.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "F9164A41027B43BE0F3AD1EB58EF18835D02156A2EE0EE67653C6CB1F5AA4E82"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer.PageFiles;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer.PageFiles {
    
    
    /// <summary>
    /// pgViewTeamDetails
    /// </summary>
    public partial class pgViewTeamDetails : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeamDetails;
        
        #line default
        #line hidden
        
        
        #line 35 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lblTeamName;
        
        #line default
        #line hidden
        
        
        #line 36 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeamSport;
        
        #line default
        #line hidden
        
        
        #line 37 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeamSport;
        
        #line default
        #line hidden
        
        
        #line 38 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeamGender;
        
        #line default
        #line hidden
        
        
        #line 39 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeamGender;
        
        #line default
        #line hidden
        
        
        #line 40 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblDescription;
        
        #line default
        #line hidden
        
        
        #line 41 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtDescLabel;
        
        #line default
        #line hidden
        
        
        #line 42 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtDescription;
        
        #line default
        #line hidden
        
        
        #line 49 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeamLeagues;
        
        #line default
        #line hidden
        
        
        #line 59 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtLeagueInfo;
        
        #line default
        #line hidden
        
        
        #line 60 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datLeagueList;
        
        #line default
        #line hidden
        
        
        #line 76 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblLeagueEmptyGrid;
        
        #line default
        #line hidden
        
        
        #line 81 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grnUpcomingGames;
        
        #line default
        #line hidden
        
        
        #line 87 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtUpcomingGames;
        
        #line default
        #line hidden
        
        
        #line 88 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datUpcomingGamesList;
        
        #line default
        #line hidden
        
        
        #line 104 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblUpcomingEmptyGrid;
        
        #line default
        #line hidden
        
        
        #line 105 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCreatePractice;
        
        #line default
        #line hidden
        
        
        #line 106 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnRemovePractice;
        
        #line default
        #line hidden
        
        
        #line 111 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdPreviousGames;
        
        #line default
        #line hidden
        
        
        #line 117 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock txtPreviousGames;
        
        #line default
        #line hidden
        
        
        #line 118 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid datPreviousGamesList;
        
        #line default
        #line hidden
        
        
        #line 134 "PageFiles\Teams\pgViewTeamDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPrevEmptyGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/teams/pgviewteamdetails.xaml" +
                    "", System.UriKind.Relative);
            
            #line 1 "PageFiles\Teams\pgViewTeamDetails.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "PageFiles\Teams\pgViewTeamDetails.xaml"
            ((Extremely_Casual_Game_Organizer.PageFiles.pgViewTeamDetails)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            
            #line 9 "PageFiles\Teams\pgViewTeamDetails.xaml"
            ((Extremely_Casual_Game_Organizer.PageFiles.pgViewTeamDetails)(target)).Unloaded += new System.Windows.RoutedEventHandler(this.Page_Unloaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.grdTeamDetails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.lblTeamName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.lblTeamSport = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.txtTeamSport = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.lblTeamGender = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.txtTeamGender = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.lblDescription = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.txtDescLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.txtDescription = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.grdTeamLeagues = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.txtLeagueInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.datLeagueList = ((System.Windows.Controls.DataGrid)(target));
            
            #line 60 "PageFiles\Teams\pgViewTeamDetails.xaml"
            this.datLeagueList.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.datLeagueList_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 14:
            this.lblLeagueEmptyGrid = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.grnUpcomingGames = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.txtUpcomingGames = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.datUpcomingGamesList = ((System.Windows.Controls.DataGrid)(target));
            
            #line 88 "PageFiles\Teams\pgViewTeamDetails.xaml"
            this.datUpcomingGamesList.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.datUpcomingGamesList_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 18:
            this.lblUpcomingEmptyGrid = ((System.Windows.Controls.Label)(target));
            return;
            case 19:
            this.btnCreatePractice = ((System.Windows.Controls.Button)(target));
            
            #line 105 "PageFiles\Teams\pgViewTeamDetails.xaml"
            this.btnCreatePractice.Click += new System.Windows.RoutedEventHandler(this.btnCreatePractice_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.btnRemovePractice = ((System.Windows.Controls.Button)(target));
            
            #line 106 "PageFiles\Teams\pgViewTeamDetails.xaml"
            this.btnRemovePractice.Click += new System.Windows.RoutedEventHandler(this.btnRemovePractice_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.grdPreviousGames = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.txtPreviousGames = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 23:
            this.datPreviousGamesList = ((System.Windows.Controls.DataGrid)(target));
            
            #line 118 "PageFiles\Teams\pgViewTeamDetails.xaml"
            this.datPreviousGamesList.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.datPreviousGamesList_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 24:
            this.lblPrevEmptyGrid = ((System.Windows.Controls.Label)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

