#pragma checksum "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8E961956A148C1D946AD921E6C892C617E984CB180B593CF1BF615DC78F7D01F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer.PageFiles.Teams.Utility;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer.PageFiles.Teams.Utility {
    
    
    /// <summary>
    /// PopUpPlayerSearch
    /// </summary>
    public partial class PopUpPlayerSearch : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Extremely_Casual_Game_Organizer.PageFiles.Teams.Utility.PopUpPlayerSearch PopUpPlayerSearch1;
        
        #line default
        #line hidden
        
        
        #line 17 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dtaGridMember;
        
        #line default
        #line hidden
        
        
        #line 18 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFirstname;
        
        #line default
        #line hidden
        
        
        #line 19 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFamilyName;
        
        #line default
        #line hidden
        
        
        #line 20 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtEmail;
        
        #line default
        #line hidden
        
        
        #line 21 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblFirstName;
        
        #line default
        #line hidden
        
        
        #line 22 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblFamilyName;
        
        #line default
        #line hidden
        
        
        #line 23 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmail;
        
        #line default
        #line hidden
        
        
        #line 24 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSelect;
        
        #line default
        #line hidden
        
        
        #line 25 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 26 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button bntCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/teams/utility/popupplayersea" +
                    "rch.xaml", System.UriKind.Relative);
            
            #line 1 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.PopUpPlayerSearch1 = ((Extremely_Casual_Game_Organizer.PageFiles.Teams.Utility.PopUpPlayerSearch)(target));
            return;
            case 2:
            this.dtaGridMember = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 3:
            this.txtFirstname = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.txtFamilyName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.txtEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.lblFirstName = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.lblFamilyName = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.lblEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.btnSelect = ((System.Windows.Controls.Button)(target));
            
            #line 24 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
            this.btnSelect.Click += new System.Windows.RoutedEventHandler(this.btnSelect_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 25 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.btnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.bntCancel = ((System.Windows.Controls.Button)(target));
            
            #line 26 "PageFiles\Teams\Utility\PopUpPlayerSearch.xaml"
            this.bntCancel.Click += new System.Windows.RoutedEventHandler(this.bntCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

