#pragma checksum "PageFiles\Tournaments\pgGenerateTournamentGame.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D77FC31C917F54F765C9ADB9395ECA511316F1645D1F6B4AECBDAEE9E6723068"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer {
    
    
    /// <summary>
    /// pgGenerateTournamentGame
    /// </summary>
    public partial class pgGenerateTournamentGame : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 15 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lbTeam;
        
        #line default
        #line hidden
        
        
        #line 17 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lbTournament;
        
        #line default
        #line hidden
        
        
        #line 19 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ddTournament;
        
        #line default
        #line hidden
        
        
        #line 20 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGenerate;
        
        #line default
        #line hidden
        
        
        #line 21 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        
        #line 22 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOpenTournamentPage;
        
        #line default
        #line hidden
        
        
        #line 23 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNbreOfTeam;
        
        #line default
        #line hidden
        
        
        #line 24 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnDeleteAllGames;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/tournaments/pggeneratetourna" +
                    "mentgame.xaml", System.UriKind.Relative);
            
            #line 1 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.lbTeam = ((System.Windows.Controls.ListBox)(target));
            return;
            case 2:
            this.lbTournament = ((System.Windows.Controls.ListBox)(target));
            return;
            case 3:
            this.ddTournament = ((System.Windows.Controls.ComboBox)(target));
            
            #line 19 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            this.ddTournament.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ddTournament_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btnGenerate = ((System.Windows.Controls.Button)(target));
            
            #line 20 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            this.btnGenerate.Click += new System.Windows.RoutedEventHandler(this.btnGenerate_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 21 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnGenerate_Copy_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.btnOpenTournamentPage = ((System.Windows.Controls.Button)(target));
            
            #line 22 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            this.btnOpenTournamentPage.Click += new System.Windows.RoutedEventHandler(this.btnOpenTournamentPage_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.lblNbreOfTeam = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.btnDeleteAllGames = ((System.Windows.Controls.Button)(target));
            
            #line 24 "PageFiles\Tournaments\pgGenerateTournamentGame.xaml"
            this.btnDeleteAllGames.Click += new System.Windows.RoutedEventHandler(this.btnDeleteAllGames_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

