#pragma checksum "PageFiles\Games\pgAddEditGame.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "831F9141DF0DD57ABAB2D5623B076598673B9AB99433D5063287F318441A6DA4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer.PageFiles.Games;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer.PageFiles.Games {
    
    
    /// <summary>
    /// pgAddEditGame
    /// </summary>
    public partial class pgAddEditGame : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 20 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdDetails;
        
        #line default
        #line hidden
        
        
        #line 39 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblHeader;
        
        #line default
        #line hidden
        
        
        #line 40 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVenueName;
        
        #line default
        #line hidden
        
        
        #line 41 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameStreet;
        
        #line default
        #line hidden
        
        
        #line 42 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblZipCode;
        
        #line default
        #line hidden
        
        
        #line 43 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCityState;
        
        #line default
        #line hidden
        
        
        #line 44 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameDate;
        
        #line default
        #line hidden
        
        
        #line 45 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameTime;
        
        #line default
        #line hidden
        
        
        #line 46 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameType;
        
        #line default
        #line hidden
        
        
        #line 48 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtVenueName;
        
        #line default
        #line hidden
        
        
        #line 49 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtStreet;
        
        #line default
        #line hidden
        
        
        #line 50 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtZip;
        
        #line default
        #line hidden
        
        
        #line 51 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtState;
        
        #line default
        #line hidden
        
        
        #line 52 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dateGameDate;
        
        #line default
        #line hidden
        
        
        #line 53 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboTimeHour;
        
        #line default
        #line hidden
        
        
        #line 54 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboTimeMinutes;
        
        #line default
        #line hidden
        
        
        #line 55 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboAMPM;
        
        #line default
        #line hidden
        
        
        #line 56 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmboSports;
        
        #line default
        #line hidden
        
        
        #line 60 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSaveAdd;
        
        #line default
        #line hidden
        
        
        #line 61 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 66 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam1Details;
        
        #line default
        #line hidden
        
        
        #line 74 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam1Name;
        
        #line default
        #line hidden
        
        
        #line 75 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtTeam1;
        
        #line default
        #line hidden
        
        
        #line 76 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam1Score;
        
        #line default
        #line hidden
        
        
        #line 77 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeam1Score;
        
        #line default
        #line hidden
        
        
        #line 79 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTeam1Search;
        
        #line default
        #line hidden
        
        
        #line 82 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam1Roster;
        
        #line default
        #line hidden
        
        
        #line 83 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox listTeam1RosterList;
        
        #line default
        #line hidden
        
        
        #line 88 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam2Details;
        
        #line default
        #line hidden
        
        
        #line 96 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam2Name;
        
        #line default
        #line hidden
        
        
        #line 97 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtTeam2;
        
        #line default
        #line hidden
        
        
        #line 98 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam2Score;
        
        #line default
        #line hidden
        
        
        #line 99 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeam2Score;
        
        #line default
        #line hidden
        
        
        #line 101 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTeam2Search;
        
        #line default
        #line hidden
        
        
        #line 104 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam2Roster;
        
        #line default
        #line hidden
        
        
        #line 105 "PageFiles\Games\pgAddEditGame.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox listTeam2RosterList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/games/pgaddeditgame.xaml", System.UriKind.Relative);
            
            #line 1 "PageFiles\Games\pgAddEditGame.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "PageFiles\Games\pgAddEditGame.xaml"
            ((Extremely_Casual_Game_Organizer.PageFiles.Games.pgAddEditGame)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Page_Loaded);
            
            #line default
            #line hidden
            
            #line 9 "PageFiles\Games\pgAddEditGame.xaml"
            ((Extremely_Casual_Game_Organizer.PageFiles.Games.pgAddEditGame)(target)).Unloaded += new System.Windows.RoutedEventHandler(this.Page_Unloaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.grdDetails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.lblHeader = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblVenueName = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblGameStreet = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblZipCode = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.lblCityState = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.lblGameDate = ((System.Windows.Controls.Label)(target));
            return;
            case 9:
            this.lblGameTime = ((System.Windows.Controls.Label)(target));
            return;
            case 10:
            this.lblGameType = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.txtVenueName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.txtStreet = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.txtZip = ((System.Windows.Controls.TextBox)(target));
            
            #line 50 "PageFiles\Games\pgAddEditGame.xaml"
            this.txtZip.LostFocus += new System.Windows.RoutedEventHandler(this.txtZip_LostFocus);
            
            #line default
            #line hidden
            return;
            case 14:
            this.txtState = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.dateGameDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 16:
            this.cmboTimeHour = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 17:
            this.cmboTimeMinutes = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.cmboAMPM = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.cmboSports = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 20:
            this.btnSaveAdd = ((System.Windows.Controls.Button)(target));
            
            #line 60 "PageFiles\Games\pgAddEditGame.xaml"
            this.btnSaveAdd.Click += new System.Windows.RoutedEventHandler(this.btnSaveAdd_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 61 "PageFiles\Games\pgAddEditGame.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.grdTeam1Details = ((System.Windows.Controls.Grid)(target));
            return;
            case 23:
            this.lblTeam1Name = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.txtTeam1 = ((System.Windows.Controls.Label)(target));
            return;
            case 25:
            this.lblTeam1Score = ((System.Windows.Controls.Label)(target));
            return;
            case 26:
            this.txtTeam1Score = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.btnTeam1Search = ((System.Windows.Controls.Button)(target));
            
            #line 79 "PageFiles\Games\pgAddEditGame.xaml"
            this.btnTeam1Search.Click += new System.Windows.RoutedEventHandler(this.btnTeam1Search_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.grdTeam1Roster = ((System.Windows.Controls.Grid)(target));
            return;
            case 29:
            this.listTeam1RosterList = ((System.Windows.Controls.ListBox)(target));
            return;
            case 30:
            this.grdTeam2Details = ((System.Windows.Controls.Grid)(target));
            return;
            case 31:
            this.lblTeam2Name = ((System.Windows.Controls.Label)(target));
            return;
            case 32:
            this.txtTeam2 = ((System.Windows.Controls.Label)(target));
            return;
            case 33:
            this.lblTeam2Score = ((System.Windows.Controls.Label)(target));
            return;
            case 34:
            this.txtTeam2Score = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.btnTeam2Search = ((System.Windows.Controls.Button)(target));
            
            #line 101 "PageFiles\Games\pgAddEditGame.xaml"
            this.btnTeam2Search.Click += new System.Windows.RoutedEventHandler(this.btnTeam2Search_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.grdTeam2Roster = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.listTeam2RosterList = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

