#pragma checksum "PageFiles\Games\pgViewGameDetails.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "4E80981F0B8DCC5FC18FE5BBFD37B38B9FD5DB9F2C4EC540AAE6764C8431EC56"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer.PageFiles;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer.PageFiles {
    
    
    /// <summary>
    /// pgViewGameDetails
    /// </summary>
    public partial class pgViewGameDetails : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Extremely_Casual_Game_Organizer.PageFiles.pgViewGameDetails pageViewGameDetails;
        
        #line default
        #line hidden
        
        
        #line 19 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdDetails;
        
        #line default
        #line hidden
        
        
        #line 38 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdScore;
        
        #line default
        #line hidden
        
        
        #line 48 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblScore;
        
        #line default
        #line hidden
        
        
        #line 49 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam1Winner;
        
        #line default
        #line hidden
        
        
        #line 50 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam2Winner;
        
        #line default
        #line hidden
        
        
        #line 52 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeam1Score;
        
        #line default
        #line hidden
        
        
        #line 53 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtToLabel;
        
        #line default
        #line hidden
        
        
        #line 54 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTeam2Score;
        
        #line default
        #line hidden
        
        
        #line 59 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameDetails;
        
        #line default
        #line hidden
        
        
        #line 60 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVenueName;
        
        #line default
        #line hidden
        
        
        #line 61 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameLocaiton;
        
        #line default
        #line hidden
        
        
        #line 62 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameDate;
        
        #line default
        #line hidden
        
        
        #line 63 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameTime;
        
        #line default
        #line hidden
        
        
        #line 64 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblGameType;
        
        #line default
        #line hidden
        
        
        #line 66 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtLocation;
        
        #line default
        #line hidden
        
        
        #line 67 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtVenueName;
        
        #line default
        #line hidden
        
        
        #line 68 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDate;
        
        #line default
        #line hidden
        
        
        #line 69 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTime;
        
        #line default
        #line hidden
        
        
        #line 70 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSport;
        
        #line default
        #line hidden
        
        
        #line 74 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam1Details;
        
        #line default
        #line hidden
        
        
        #line 82 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam1Name;
        
        #line default
        #line hidden
        
        
        #line 83 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtTeam1;
        
        #line default
        #line hidden
        
        
        #line 86 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam1Roster;
        
        #line default
        #line hidden
        
        
        #line 87 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox listTeam1RosterList;
        
        #line default
        #line hidden
        
        
        #line 92 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam2Details;
        
        #line default
        #line hidden
        
        
        #line 100 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblTeam2Name;
        
        #line default
        #line hidden
        
        
        #line 101 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label txtTeam2;
        
        #line default
        #line hidden
        
        
        #line 104 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grdTeam2Roster;
        
        #line default
        #line hidden
        
        
        #line 105 "PageFiles\Games\pgViewGameDetails.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox listTeam2RosterList;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/games/pgviewgamedetails.xaml" +
                    "", System.UriKind.Relative);
            
            #line 1 "PageFiles\Games\pgViewGameDetails.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pageViewGameDetails = ((Extremely_Casual_Game_Organizer.PageFiles.pgViewGameDetails)(target));
            
            #line 9 "PageFiles\Games\pgViewGameDetails.xaml"
            this.pageViewGameDetails.Loaded += new System.Windows.RoutedEventHandler(this.pageViewGameDetails_Loaded);
            
            #line default
            #line hidden
            
            #line 9 "PageFiles\Games\pgViewGameDetails.xaml"
            this.pageViewGameDetails.Unloaded += new System.Windows.RoutedEventHandler(this.pageViewGameDetails_Unloaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.grdDetails = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.grdScore = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.lblScore = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblTeam1Winner = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblTeam2Winner = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.txtTeam1Score = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtToLabel = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.txtTeam2Score = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.lblGameDetails = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.lblVenueName = ((System.Windows.Controls.Label)(target));
            return;
            case 12:
            this.lblGameLocaiton = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.lblGameDate = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.lblGameTime = ((System.Windows.Controls.Label)(target));
            return;
            case 15:
            this.lblGameType = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.txtLocation = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.txtVenueName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.txtDate = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.txtTime = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.txtSport = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.grdTeam1Details = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.lblTeam1Name = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.txtTeam1 = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.grdTeam1Roster = ((System.Windows.Controls.Grid)(target));
            return;
            case 25:
            this.listTeam1RosterList = ((System.Windows.Controls.ListBox)(target));
            return;
            case 26:
            this.grdTeam2Details = ((System.Windows.Controls.Grid)(target));
            return;
            case 27:
            this.lblTeam2Name = ((System.Windows.Controls.Label)(target));
            return;
            case 28:
            this.txtTeam2 = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.grdTeam2Roster = ((System.Windows.Controls.Grid)(target));
            return;
            case 30:
            this.listTeam2RosterList = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

