#pragma checksum "PageFiles\Utility\pgResetPassword.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5E9AF17E4A0B69B7C9786E5D3F8B6E840B7EE8F7AF4128354050FE34D19A979A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Extremely_Casual_Game_Organizer.PageFiles;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Extremely_Casual_Game_Organizer.PageFiles {
    
    
    /// <summary>
    /// pgResetPassword
    /// </summary>
    public partial class pgResetPassword : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 1 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Extremely_Casual_Game_Organizer.PageFiles.pgResetPassword pageResetPassword;
        
        #line default
        #line hidden
        
        
        #line 29 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblPageTitle;
        
        #line default
        #line hidden
        
        
        #line 30 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblEmail;
        
        #line default
        #line hidden
        
        
        #line 31 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblCurrentPW;
        
        #line default
        #line hidden
        
        
        #line 32 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblNewPW;
        
        #line default
        #line hidden
        
        
        #line 33 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblConfirmPW;
        
        #line default
        #line hidden
        
        
        #line 35 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtEmail;
        
        #line default
        #line hidden
        
        
        #line 36 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox txtCurrentPW;
        
        #line default
        #line hidden
        
        
        #line 37 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox txtNewPW;
        
        #line default
        #line hidden
        
        
        #line 38 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox txtConfirmPW;
        
        #line default
        #line hidden
        
        
        #line 41 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        
        #line 42 "PageFiles\Utility\pgResetPassword.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Extremely Casual Game Organizer;component/pagefiles/utility/pgresetpassword.xaml" +
                    "", System.UriKind.Relative);
            
            #line 1 "PageFiles\Utility\pgResetPassword.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.pageResetPassword = ((Extremely_Casual_Game_Organizer.PageFiles.pgResetPassword)(target));
            
            #line 9 "PageFiles\Utility\pgResetPassword.xaml"
            this.pageResetPassword.Loaded += new System.Windows.RoutedEventHandler(this.pgResetPassword_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.lblPageTitle = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.lblEmail = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblCurrentPW = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblNewPW = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.lblConfirmPW = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.txtEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtCurrentPW = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 9:
            this.txtNewPW = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 10:
            this.txtConfirmPW = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 11:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 41 "PageFiles\Utility\pgResetPassword.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.btnSave = ((System.Windows.Controls.Button)(target));
            
            #line 42 "PageFiles\Utility\pgResetPassword.xaml"
            this.btnSave.Click += new System.Windows.RoutedEventHandler(this.btnSave_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

